version: "3"

services:
  home-nginx:
    image: nginx:latest
    volumes:
      - "./home:/usr/share/nginx/html"
    environment:
      TZ: "Asia/Shanghai"
    restart: always
    ports:
      - "18000:80"
  app-nginx:
    image: nginx:latest
    volumes:
      - "./app:/usr/share/nginx/html"
    environment:
      TZ: "Asia/Shanghai"
    restart: always
    ports:
      - "13000:80"
  dynamic-nginx:
    image: nginx:latest
    volumes:
      - "./dynamic:/usr/share/nginx/html"
    environment:
      TZ: "Asia/Shanghai"
    restart: always
    ports:
      - "19000:80"
